//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAI.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatAI.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ChatGPT using Azure AI.
        /// </summary>
        internal static string AboutStringId_AppDescription {
            get {
                return ResourceManager.GetString("AboutStringId.AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Studio A&amp;T s.r.l..
        /// </summary>
        internal static string AboutStringId_Company {
            get {
                return ResourceManager.GetString("AboutStringId.Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current version : {0}.
        /// </summary>
        internal static string AboutStringId_CurrentVersion {
            get {
                return ResourceManager.GetString("AboutStringId.CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Power by {0}.
        /// </summary>
        internal static string AboutStringId_PowerBy {
            get {
                return ResourceManager.GetString("AboutStringId.PowerBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://www.studioat.it.
        /// </summary>
        internal static string AboutStringId_SiteWebCompany {
            get {
                return ResourceManager.GetString("AboutStringId.SiteWebCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string ChatStringId_PopupCancel {
            get {
                return ResourceManager.GetString("ChatStringId.PopupCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your text message.
        /// </summary>
        internal static string ChatStringId_TextMessage {
            get {
                return ResourceManager.GetString("ChatStringId.TextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        internal static string MainStringId_TabAbout {
            get {
                return ResourceManager.GetString("MainStringId.TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chat.
        /// </summary>
        internal static string MainStringId_TabChatAI {
            get {
                return ResourceManager.GetString("MainStringId.TabChatAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        internal static string MainStringId_TabSettings {
            get {
                return ResourceManager.GetString("MainStringId.TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Api key.
        /// </summary>
        internal static string SettingsStringId_ApiKey {
            get {
                return ResourceManager.GetString("SettingsStringId.ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        internal static string SettingsStringId_CaptionSave {
            get {
                return ResourceManager.GetString("SettingsStringId.CaptionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chat deployment name.
        /// </summary>
        internal static string SettingsStringId_ChatClientDeploymentName {
            get {
                return ResourceManager.GetString("SettingsStringId.ChatClientDeploymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a End point.
        /// </summary>
        internal static string SettingsStringId_EndPoint {
            get {
                return ResourceManager.GetString("SettingsStringId.EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error retrieving credential.
        /// </summary>
        internal static string SettingsStringId_ErrorRetrievingCredential {
            get {
                return ResourceManager.GetString("SettingsStringId.ErrorRetrievingCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error store {0}!.
        /// </summary>
        internal static string SettingsStringId_ErrorStoreSetting {
            get {
                return ResourceManager.GetString("SettingsStringId.ErrorStoreSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Field required.
        /// </summary>
        internal static string SettingsStringId_FieldRequired {
            get {
                return ResourceManager.GetString("SettingsStringId.FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Image deployment name.
        /// </summary>
        internal static string SettingsStringId_ImageClientDeploymentName {
            get {
                return ResourceManager.GetString("SettingsStringId.ImageClientDeploymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No valid credential.
        /// </summary>
        internal static string SettingsStringId_NoValidValueCredential {
            get {
                return ResourceManager.GetString("SettingsStringId.NoValidValueCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Saved successfully.
        /// </summary>
        internal static string SettingsStringId_SaveCredentialSuccess {
            get {
                return ResourceManager.GetString("SettingsStringId.SaveCredentialSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        internal static string SystemStringId_Alert_ButtonCancel {
            get {
                return ResourceManager.GetString("SystemStringId.Alert_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        internal static string SystemStringId_Alert_TitleError {
            get {
                return ResourceManager.GetString("SystemStringId.Alert_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning.
        /// </summary>
        internal static string SystemStringId_Alert_TitleWarning {
            get {
                return ResourceManager.GetString("SystemStringId.Alert_TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        internal static string SystemStringId_No {
            get {
                return ResourceManager.GetString("SystemStringId.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yes.
        /// </summary>
        internal static string SystemStringId_Yes {
            get {
                return ResourceManager.GetString("SystemStringId.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Build history.
        /// </summary>
        internal static string VersionTrackingStringId_BuildHistory {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.BuildHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current build.
        /// </summary>
        internal static string VersionTrackingStringId_CurrentBuild {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.CurrentBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current version.
        /// </summary>
        internal static string VersionTrackingStringId_CurrentVersion {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First installed build.
        /// </summary>
        internal static string VersionTrackingStringId_FirstInstalledBuild {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.FirstInstalledBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First installed version.
        /// </summary>
        internal static string VersionTrackingStringId_FirstInstalledVersion {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.FirstInstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Is first launch ever.
        /// </summary>
        internal static string VersionTrackingStringId_IsFirstLaunchEver {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.IsFirstLaunchEver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Is first launch for current build.
        /// </summary>
        internal static string VersionTrackingStringId_IsFirstLaunchForCurrentBuild {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.IsFirstLaunchForCurrentBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Is first launch for current version.
        /// </summary>
        internal static string VersionTrackingStringId_IsFirstLaunchForCurrentVersion {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.IsFirstLaunchForCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Previous build.
        /// </summary>
        internal static string VersionTrackingStringId_PreviousBuild {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.PreviousBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Previous version.
        /// </summary>
        internal static string VersionTrackingStringId_PreviousVersion {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.PreviousVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version history.
        /// </summary>
        internal static string VersionTrackingStringId_VersionHistory {
            get {
                return ResourceManager.GetString("VersionTrackingStringId.VersionHistory", resourceCulture);
            }
        }
    }
}
